# .github/workflows/deploy-backend.yml

name: Manually Deploy Backend

# This section allows the workflow to be triggered manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      # This creates a dropdown menu to select the branch to deploy
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - main

# --- THIS ENV BLOCK HAS BEEN ADDED BACK IN ---
# It defines all the variables needed for the deployment steps.
env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: "file-sharing-app-dev-flask-app"
  ECS_CLUSTER_NAME_DEV: "file-sharing-app-dev-cluster"
  ECS_CLUSTER_NAME_PROD: "your-PROD-ecs-cluster-name" # Placeholder for prod
  ECS_SERVICE_NAME_DEV: "file-sharing-app-dev-service"
  ECS_SERVICE_NAME_PROD: "your-PROD-ecs-service-name" # Placeholder for prod
  IAM_ROLE_TO_ASSUME: "arn:aws:iam::481509955802:role/githubactions-radulupan-aws-fileshare-plus-role"

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest

    # This logic now reads from the manual dropdown input to set the environment name
    env:
      TARGET_ENV: ${{ github.event.inputs.branch == 'main' && 'prod' || 'dev' }}

    steps:
      # We check out the specific branch you selected in the dropdown
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update ECS Service
        env:
          ECS_CLUSTER: ${{ env.TARGET_ENV == 'prod' && env.ECS_CLUSTER_NAME_PROD || env.ECS_CLUSTER_NAME_DEV }}
          ECS_SERVICE: ${{ env.TARGET_ENV == 'prod' && env.ECS_SERVICE_NAME_PROD || env.ECS_SERVICE_NAME_DEV }}
        run: |
          echo "Deploying to the ${{ env.TARGET_ENV }} environment..."
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment