# .github/workflows/deploy-backend.yml

name: Manually Deploy Backend

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - main

# NOTE: This env block only contains global values.
env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY_NAME: "file-sharing-app-radulupan-test"
  IAM_ROLE_TO_ASSUME: "arn:aws:iam::481509955802:role/githubactions-radulupan-aws-fileshare-plus-role"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    env:
      TARGET_ENV: ${{ github.event.inputs.branch == 'main' && 'prod' || 'dev' }}
    steps:
      # --- STEP 1: Configure credentials ---
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: 'false'

      # --- STEP 2: Explicitly fetch SSM parameters ---
      - name: Fetch Configuration from SSM Parameter Store
        run: |
          echo "Fetching config for ${{ env.TARGET_ENV }} from path /fileshare/${{ env.TARGET_ENV }}"
          # Get parameters, transform them to VAR_NAME=VALUE format,
          # convert the name to uppercase, and append to the job's environment file.
          aws ssm get-parameters-by-path --path "/fileshare/${{ env.TARGET_ENV }}" --query "Parameters[*]" --output json | \
          jq -r '.[] | .Name + "=" + .Value' | \
          sed -e "s|/fileshare/${{ env.TARGET_ENV }}/||" -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          COMMIT_SHA_TAG: ${{ github.sha }}
          BRANCH_TAG: ${{ github.event.inputs.branch }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$COMMIT_SHA_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$COMMIT_SHA_TAG $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$BRANCH_TAG
          echo "Pushing tag: $COMMIT_SHA_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$COMMIT_SHA_TAG
          echo "Pushing tag: $BRANCH_TAG"
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_NAME:$BRANCH_TAG

      - name: Update ECS Service
        run: |
          echo "Deploying to the ${{ env.TARGET_ENV }} environment..."
          echo "Using Cluster: ${{ env.ECS_CLUSTER_NAME }}"
          echo "Updating Service: ${{ env.ECS_SERVICE_NAME }}"
          aws ecs update-service --cluster "${{ env.ECS_CLUSTER_NAME }}" --service "${{ env.ECS_SERVICE_NAME }}" --force-new-deployment

