# .github/workflows/deploy.yml

name: CI & CD Pipeline for AWS FileShare App

on:
  push:
    branches:
      - main
      - dev

env:
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: "file-sharing-app-dev-flask-app"
  FRONTEND_S3_BUCKET_DEV: "file-sharing-app-37016c887ae9d041"
  FRONTEND_S3_BUCKET_PROD: "your-PROD-frontend-bucket-name"
  CLOUDFRONT_DISTRIBUTION_ID_DEV: "E12N0TVJQ8PG2Q"
  CLOUDFRONT_DISTRIBUTION_ID_PROD: "your-PROD-cloudfront-dist-id"
  ECS_CLUSTER_NAME_DEV: "file-sharing-app-dev-cluster"
  ECS_CLUSTER_NAME_PROD: "your-PROD-ecs-cluster-name"
  ECS_SERVICE_NAME_DEV: "file-sharing-app-dev-service"
  ECS_SERVICE_NAME_PROD: "your-PROD-ecs-service-name"
  REACT_APP_BACKEND_API_URL: "https://cf.aws.lupan.ca"
  IAM_ROLE_TO_ASSUME: "arn:aws:iam::481509955802:role/githubactions-radulupan-aws-fileshare-plus-role"

permissions:
  id-token: write
  contents: read

jobs:
  # --- THIS JOB HAS BEEN COMPLETELY REWRITTEN ---
  detect-changes:
    name: Detect File Changes
    runs-on: ubuntu-latest
    outputs:
      backend: ${{ steps.check_backend.outputs.any_changed }}
      frontend: ${{ steps.check_frontend.outputs.any_changed }}
      infra: ${{ steps.check_infra.outputs.any_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history is still best practice

      - name: Check for backend changes
        id: check_backend
        uses: tj-actions/changed-files@v44 # Using the new, reliable action
        with:
          files: backend/**

      - name: Check for frontend changes
        id: check_frontend
        uses: tj-actions/changed-files@v44
        with:
          files: frontend/**

      - name: Check for infrastructure changes
        id: check_infra
        uses: tj-actions/changed-files@v44
        with:
          files: terraform/**

      - name: Debug outputs
        run: |
          echo "Backend changed: ${{ steps.check_backend.outputs.any_changed }}"
          echo "Frontend changed: ${{ steps.check_frontend.outputs.any_changed }}"
          echo "Infra changed: ${{ steps.check_infra.outputs.any_changed }}"

  # --- NO CHANGES BELOW THIS LINE ---
  deploy-infra:
    name: Deploy Infrastructure
    needs: detect-changes
    if: needs.detect-changes.outputs.infra == 'true'
    runs-on: ubuntu-latest
    env:
      TF_ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Apply
        run: |
          cd terraform/environments/${{ env.TF_ENV }}
          terraform init
          terraform validate
          terraform apply -auto-approve -var-file=${{ env.TF_ENV }}.tfvars

  deploy-backend:
    name: Build and Deploy Backend
    needs: [detect-changes, deploy-infra]
    if: needs.detect-changes.outputs.backend == 'true' || needs.detect-changes.outputs.infra == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd backend
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Update ECS Service
        env:
          ECS_CLUSTER: ${{ github.ref_name == 'main' && env.ECS_CLUSTER_NAME_PROD || env.ECS_CLUSTER_NAME_DEV }}
          ECS_SERVICE: ${{ github.ref_name == 'main' && env.ECS_SERVICE_NAME_PROD || env.ECS_SERVICE_NAME_DEV }}
        run: aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment

  deploy-frontend:
    name: Build and Deploy Frontend
    needs: [detect-changes, deploy-infra]
    if: needs.detect-changes.outputs.frontend == 'true' || needs.detect-changes.outputs.infra == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.IAM_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies and build
        run: |
          cd frontend
          npm ci
          npm run build
        env:
          REACT_APP_BACKEND_API_URL: ${{ env.REACT_APP_BACKEND_API_URL }}
      - name: Deploy static site to S3
        env:
          S3_BUCKET: ${{ github.ref_name == 'main' && env.FRONTEND_S3_BUCKET_PROD || env.FRONTEND_S3_BUCKET_DEV }}
        run: aws s3 sync ./frontend/build s3://$S3_BUCKET --delete
      - name: Invalidate CloudFront cache
        env:
          CLOUDFRONT_ID: ${{ github.ref_name == 'main' && env.CLOUDFRONT_DISTRIBUTION_ID_PROD || env.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
        run: aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"